# .github/workflows/ci-cd.yml

name: CI/CD pour l'Infrastructure Multi-Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-plan:
    name: "Terraform Validate & Plan"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Configurez vos secrets dans les paramètres de votre dépôt GitHub
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: \${{ secrets.AZURE_CREDENTIALS }}
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '\${{ secrets.GCP_CREDENTIALS }}'

    - name: Terraform Init
      run: terraform -chdir=./terraform init

    - name: Terraform Validate
      run: terraform -chdir=./terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform -chdir=./terraform plan -no-color

  apply-infrastructure:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: validate-and-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Configurez les identifiants comme dans le job précédent
    - name: Configure Cloud Credentials
      # ... (étapes de configuration des identifiants) ...
      
    - name: Terraform Init
      run: terraform -chdir=./terraform init

    - name: Terraform Apply
      # ATTENTION: --auto-approve est utilisé pour l'automatisation.
      # En production, préférez une approbation manuelle via les "environments" de GitHub.
      run: terraform -chdir=./terraform apply --auto-approve
